# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4faa720c3714e1f53156493e528e3107847640384575077c7823b927ba8b663739274f8ecd792f9b9daa3ec185156e08095f769566e31896f97f0d4cc1f8d7d7

test:
  secret_key_base: e618a77e99553c0187c26e44821efc02721ee7e4c99af07dedf26d60d00cc40b06ce657e95092d5e5807adb3281ecd8fb027df1600f1e598d9845d4a46eb8990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
